content:
  - name: posts
    label: Posts
    path: src/content
    type: collection
    fields:
      - { name: title, label: Title, type: string  }
      - { name: description, label: Description, type: string  }
      - { name: pubDate, label: pubDate, type: date  }
      - { name: updatedDate, label: updatedDate, type: date  }
      - { name: heroImage, label: heroImage, type: string  }
      - { name: body, label: Body, type: rich-text  }